spring:
  application:
    name: CrateGameInterface
  datasource:
    url: jdbc:postgresql://192.168.0.104:5432/crategame
    username: crategametest
    password: crategameisascum
    driver-class-name: org.postgresql.Driver

    jpa:
      open-in-view: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
logging:
  level:
    liquibase: DEBUG

app:
  base-url: http://192.168.0.101:8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics  # or "*" to expose all
  endpoint:
    health:
      show-details: always