spring:
  application:
    name: CrateGameInterface
  datasource:
    url: jdbc:postgresql://192.168.0.104:5432/yourdb
    username: crategametest
    password: crategameisascum
    driver-class-name: org.postgresql.Driver

    liquibase:
      change-log: classpath:db/changelog/db.changelog-master.yaml